### PR TITLE
Update Cloudwatch distribution

### PR DESCRIPTION
**Pull request by m1yag1**
- Updated Lambda function to default to correct bucket.
- Added s3 readonly to the lambda function
- Generated SAM template for updates to the stack

### CODE REVIEW

**Review by karenc — COMMENTED** [review]
I tried running the deploy command and got some error:

```
karen@yachiyo:~/src/rap-spike-lambda$ aws cloudformation deploy --template-file cf-templates/cf-cloudfront-content-buckets.yaml --region us-east-1 --stack-name rap-distribution --tags Project=rap-spike-lambda Application=rap-spike-lambda Environment=dev Owner=karen

Waiting for changeset to be created..

Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [LambdaEdgeFunction] is invalid. 'CodeUri' is not a valid S3 Uri of the form "s3://bucket/key" with optional versionId query parameter.
```

**Comment by m1yag1** [comment]
@karen That command only needs to ran once to create the stack. To do updates you need to run the `package` command and the `update-stack` command.

I'll add a comment to the README to make that more clear.

**Comment by m1yag1** [comment]
In the README. i have a note that the package command will substitute the correct s3 bucket in the proper locations.

> This will package up the lambda function, upload to the s3 bucket, and generate a new template that has the s3 bucket substituted in the proper locations of the template.

**Comment by karenc** [comment]
@mike so there's only one distribution and we're sharing it and updating the same one?

**Comment by m1yag1** [comment]
@karenc Yes, it's meant to act as a staging environment the way I have it setup. If there were to be changes we would merge the changes in GitHub and then run the package + update stack commands to make sure the changes took effect in staging. If we wanted to later we could set it up so we could approve staging and it would automatically update production.

When you run the commands AWS creates what they call a "change set". It only updates the things that have changed. You can even remove things like Roles and it will remove the roles.

For example, after this PR is merged I'm going to make changes to the lambda function via the github repo. To get those changes pushed up to the distribution i'll run the commands and then the changes will be live.

**Review by karenc — APPROVED** [review]
I was able to run `aws cloudformation package` and `aws cloudformation update-stack` so :+1:

**Pull request merged**
